<div class="sous-boite">
	<p>Dans ce contexte, le premier congrès d’orientation de Québec solidaire adoptait une proposition sur l’Assemblée constituante qui montrait la forme que pourrait prendre l’expression de la souveraineté populaire au Québec. Il s’agit de préciser maintenant ce qu’est, pour nous, le projet de souveraineté et les rapports qu’un Québec souverain établirait avec les autres peuples de la planète. Nos discussions viseront également à déterminer les moyens d’y parvenir et les alliances que nous devrons construire à cette fin.</p>
	<p>Pour concrétiser ce projet, nous proposons l’élection d ‘une assemblée constituante qui aura comme mandat de définir de façon démocratique le statut du Québec et ses institutions politiques. Notre discussion permettra à Québec solidaire d’élaborer des propositions qui nous permettront non seulement de dépasser le déficit démocratique actuel mais d’inscrire au cœur même des institutions du Québec nos aspirations à l’égalité sociale et à l’égalité entre les femmes et les hommes.</p>
	<p>Comment élargir et approfondir la démocratie représentative? Comment concrétiser une démarche de démocratie participative? Comment donner aux régions un espace démocratique véritable? Voilà des orientations à définir collectivement afin de concrétiser le projet social et national que nous voulons proposer à l’ensemble de la population du Québec.</p>
	<p>La réalisation d’un Québec pluraliste est partie prenante de notre projet politique. Il faut maintenant en préciser les tenants et aboutissants. L’intégration égalitaire et pluraliste de l’ensemble des citoyennes et citoyens du Québec à la vie économique, politique et culturelle est un défi central de la société québécoise. Il faudra donc tracer les voies de sa réalisation et définir ce que sera le creuset de cette intégration citoyenne qui nous permettra d’avancer collectivement vers une société moderne, diversifiée, pluraliste et inclusive.</p>
	<p>	C’est cette orientation globale qui nous a conduits à regrouper dans ce site et dans toute la démarche vers le programme de Québec solidaire tant les questions touchant la souveraineté, que celles relevant de la redéfinition des institutions politiques et de l’intégration des personnes issues de l’immigration.</p>
	<p>On vous invite à répondre à des questions qui permettront, nous l’espérons, de mobiliser vos réflexions, vos analyses et vos convictions pour tracer les orientations programmatiques menant à la réalisation d’un projet de société du bien commun.</p>
</div>
<div id="citations">
	<h2>Citations de la déclaration de principes</h2>
	<p id="cit1">«Le Québec et son peuple, la nation québécoise, doit disposer de tous les pouvoirs nécessaires à son plein développement aux plans social, économique, culturel et politique, ce qui lui est refusé dans le cadre fédéral. Québec solidaire opte donc pour la souveraineté. Sans être une garantie, elle est un moyen de fournir au Québec les outils nécessaires pour réaliser son projet de société et s’épanouir pleinement comme peuple.»</p>
	<p id="cit2">«L’exercice démocratique doit donc être repensé pour encourager la participation des citoyennes et des citoyens, y compris les personnes plus exclues ou marginalisées, aux choix de société. C’est ce que nous appelons la démocratie participative. (…)La démocratie représentative doit également faire l’objet d’un grand ménage pour faire davantage place à la transparence, à l’imputabilité et à l’intégrité.»</p>
	<p id="cit3">«(…) un Québec moderne, diversifié, pluraliste et inclusif. Ce Québec est bâti sur l’apport d’une importante majorité francophone, mais aussi d’une communauté anglophone aux droits historiques reconnus. Il s’enrichit aussi, et depuis longtemps, de la contribution de personnes appartenant à différentes communautés issues de l’immigration dont il faudra favoriser la participation pleine et entière au monde du travail de même qu’à la vie sociale et politique.»</p>
	<p id="cit4">«Nous considérons les Autochtones comme des peuples à part entière et nous voulons que soient reconnus, y compris par des ententes formelles, leurs droits ancestraux et territoriaux. Nous prônons des relations d’égal à égal, de nation à nation, avec les dix peuples amérindiens et le peuple inuit pour en arriver à une gestion partagée du territoire et des ressources.»</p>
</div>
